apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      # initContainers:
      # - name: "init-db"
      #   image: busybox:1.37
      #   command:
      #     - sh
      #     - -c
      #     - |
      #       until nc -z {{ .Values.postgres.host }} {{ .Values.postgres.port }}; do
      #         echo "waiting for postgres"
      #         sleep 2
      #       done
      containers:
      - name: server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
          # - name: POSTGRES_DB
          #   value: "{{ .Values.postgres.database }}"

          # - name: POSTGRES_USER
          #   value: "{{ .Values.postgres.username }}"

          # - name: POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ .Values.postgres.existingSecret }}
          #       key: {{ .Values.postgres.passwordKey }}

          # - name: POSTGRES_HOST
          #   value: "{{ .Values.postgres.host }}"

          # - name: POSTGRES_PORT
          #   value: "{{ .Values.postgres.port }}"