name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        working-directory: desktop-app
        run: npm install

      - name: build-win
        working-directory: desktop-app
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            desktop-app/dist/*.exe
            desktop-app/dist/*.msi
            desktop-app/dist/*.zip
            desktop-app/dist/*.yml
            desktop-app/dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}